### ISSUE TITLE
Hoppers stack potions in brewing stands causing deletion of items

### ISSUE THREAD

**Issue by hitakiller** [Mikedeejay2/SimpleStackPlugin#39] opened 2020-10-27 21:49 UTC
Hello !
When using stacked items in certains circumstances, they are deleted by actions.

Use a stack of enchanted_book in right side of anvil consume the entire stack instead of one book.
Same thing with brewing stand, when introducing a stack of potion to brew, completion will brew 1 potion and delete all stack.

I don't know if it's solvable but it may be noticed 'cause i think it's major issue for players wich risks to lose entire stack with some automated farms.

Thank's in advance for your help

**Comment by Mikedeejay2** [comment] 2020-10-27 22:29
Thanks for reporting! 
I've figured out what's causing the bug with the brewing stand but I am unable to reproduce the bug with the anvil. 
Are there any other plugins on your server that might be interfering with Simple Stack's stacking? 
If you are getting any errors in your server's console, could you paste one of them here? 
What version of Minecraft are you running? What server type are you running?
Thanks!

**Comment by hitakiller** [comment] 2020-10-28 00:46
You're right, i think there's one plugin wich interfere, so it's not your problem, i'll tracked it to solve this in there side.
Thank's for your help, at this moment i don't know wich is causing this issue

**Comment by Mikedeejay2** [comment] 2020-10-28 01:15
Okay, I'll close this issue for now then. 
Unfortunately, this seems to be a common problem because Simple Stack replaces parts of the item movement system. I'm working towards a more flexible system with better compatibility that should hopefully fix these things in the coming months but for now there's not much I can do about compatibility issues.
 If you have another question about this or believe that it is an issue that I can fix on my end feel free to add a comment and I'll reopen this issue.

**Closed by Mikedeejay2** 2020-10-28 01:15 UTC
Labels: bug, compatibility
